config/routes.rb
Rails.application.routes.draw do
  root "public#index"

  get "cities/:state", to: "application#cities"

  # Public Pages
  get "about-us" => "public#about"
  get "careers" => "public#careers"
  get "join" => "public#join"
  get "service" => "public#service"
  get "service_highlights" => "public#service_highlights"
  get "service_screenshots" => "public#service_screenshots"
  get "participation" => "public#participation"
  get "affiliate_locator" => "public#affiliate_locator"
  get "affiliates" => "public#affiliates"
  get "member_locator" => "public#member_locator"
  get "members" => "public#members"
  get "pricing" => "public#pricing"
  get "news" => "public#news"
  get "affiliate_agreement" => "public#affiliate_agreement"
  get "saas_agreement" => "public#saas_agreement"
  get "terms" => "public#terms"
  get "privacy" => "public#privacy"
  get "faq" => "public#faq"

  # Create Member
  resources :members_registration, only: [:new, :create]

  # User Registration
  get "users_registration" => "users_registration#new"
  post "users_registration" => "users_registration#create"

  # Affiliate Registration
  get "affiliates_registration" => "affiliates_registration#new"
  post "affiliates_registration" => "affiliates_registration#create"

  #Stripe Webhooks
  mount StripeEvent::Engine, at: '/stripe_events'

  # Contact
  get "contact" => "contact#new"
  post "contact" => "contact#create"

  # Authentication vanity routes
  get "signin" => "sessions#new", as: "signin"
  delete "signout" => "sessions#destroy", as: "signout"

  # Authentication
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # My Profile
  get "my-profile" => "profile#edit", as: "profile"
  patch "profile" => "profile#update", as: "update_profile"
  get 'request_deactivation' => 'profile#new'
  post 'request_deactivation' => 'profile#create'

  # My Settings
  resource :my_settings, only: [:show, :update]

  # Matchmaker
  get 'matchmaker' => 'matchmakers#index'
  get 'fetch_user' => 'matchmakers#fetch_user'

  # Bulletin Board
  get 'bulletins' => 'bulletins#bulletins'

  # Verify ACH account
  resource :ach, controller: 'ach', only: [:edit, :update]

  # Communities
  resources :members, path: :communities, as: :community, controller: :communities do
    resources :events, only: [:index, :show] do
      post 'create_or_switch_rsvp', on: :member
    end
  end

  get 'explore_communities' => 'communities#explore_communities'
  get 'event_search' => 'communities#event_search'
  get 'leaderboard' => 'communities#leaderboard'
  get 'user_finder' => 'communities#user_finder'
  get 'event_suggestions' => 'communities#new'
  post 'event_suggestions' => 'communities#create'
  get 'announcement_suggestions' => 'communities#new_suggest'
  post 'announcement_suggestions' => 'communities#create_suggest'
  get 'challenge_new' => 'communities#challenge_new'
  get 'challenge_index' => 'communities#challenge_index'
  post 'challenge_new' => 'communities#challenge_create'
  get 'connection_index' => 'communities#connection_index'

  # Manage
  namespace :manage do
    get "member" => "member#edit", as: "edit_member"
    patch "member" => "member#update", as: "update_member"
    namespace :social_tracker do
      get "/:name/users" => "history#users", as: :users
      get "/:name/users/:id/history" => "history#user_history", as: :member_user
      get "/:name/users/:id/history/:id" => "history#show", as: :user_history
    end
    resources :events
    resources :announcements
    resources :challenges
    resources :connections
    resources :users do
      collection do
        get 'export_user_csv'
      end
    end
  end

  # Social Tracker
  namespace :social_tracker do
    get "log" => "events#new"
    post "log" => "events#create"
    get "history" => "events#index"
    get "history/:id" => "events#show"
  end

  # Social Fitness
  namespace :social_fitness do
    get "log" => "fitness#new"
    post "log" => "fitness#create"
    get "history" => "fitness#index"
    get "history/:id" => "fitness#show"
    get "plan" => "fitness#plan"
    get "console/fitness_plans/:id" => "fitness#plan_details", as: :plan_details
  end

  # Rewards
  get "rewards" => "rewards#index"

  # Dashboard
  get "home" => "home#index"

  # Console
  get "lookups" => 'console#lookups'
  get "console" => "console#index"
  namespace :console do
    root to: "console#index", as: "root"
    resources :affiliates do
      collection do
        get 'export_csv'
      end
    end
    resources :news
    resources :rewards
    resources :manage_bulletins
    resources :event_links
    resources :fitness_plans
    resources :notifications
    resources :members do
      collection do
        get 'export_global_user_csv'
        get 'export_user_csv'
        get 'export_member_csv'
      end
      resources :users
    end
    resources :users, path: :admins, as: :admins, controller: :admins
    namespace :social_tracker do
      get "members" => "history#members"
      get "members/:name/member_csv" => "history#member_csv", as: :member_csv
      get "members/:name/users" => "history#users", as: :member
      get "members/:name/users/:id/" => "history#user_history", as: :member_user
      get "members/:name/users/:user_id/history/:id" => "history#show", as: :member_user_social_event_log
      delete "members/:name/users/:user_id/history/:id" => "history#destroy", as: :delete_social_event_log
    end

    namespace :social_fitness do
      get "members" => "history#members"
      get "members/:name/member_csv" => "history#member_csv", as: :member_csv
      get "members/:name/users" => "history#users", as: :member
      get "members/:name/users/:id/" => "history#user_history", as: :member_user
      get "members/:name/users/:user_id/history/:id" => "history#show", as: :member_user_social_fitness_log
      delete "members/:name/users/:user_id/history/:id" => "history#destroy", as: :delete_social_fitness_log
    end
  end

  # Mailbox
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    post :mark_as_deleted, on: :collection
  end

  # Media Center
  get "media_center" => "media_center#index"

  # Help
  get "help" => "help#index"
  get 'service_support' => 'help#new'
  post 'service_support' => 'help#create'

  # My Bulletins
  resources :my_bulletins

  # Invite Guests
  get "invite_guests" => "invite_guests#new"
  post "invite_guests" => "invite_guests#create"

  # Invitation Reminder
  get "invitation_reminder" => "invitation_reminder#new"
  post "invitation_reminder" => "invitation_reminder#create"

  # Event Reminder
  get "event_reminder" => "event_reminder#new"
  post "event_reminder" => "event_reminder#create"

  # Share Link
  get "share_link" => "share_link#new"
  post "share_link" => "share_link#create"

  # Affiliates
  get "affiliates_search" => "affiliates#index"

  # Discounts
  get "discounts_finder" => "discounts_finder#index"

  # Event Links
  get "event_links" => "event_links#index"

  # Report Issues
  get "issues" => "issues#new"
  post "issues" => "issues#create"

  # My Achievements
  get "my_achievements" => "my_achievements#index"

  # My Events
  get "my_events" => "my_events#index"

  # Sitemap
  get "sitemap" => "sitemap#index"

  # My Contacts
  resources :my_contacts

end

app/controllers/matchmakers_controller.rb
class MatchmakersController < ApplicationController
  before_action :require_authentication

  def index
    @users = FindUsersCommunities.new(User.joins(:hidden_field).matchmaker(authenticated_user), show_init_scope: false).call(permitted_params)
    unless @users.kind_of?(Array)
      @users = @users.order(interest_types: :asc).page(params[:page]).per(25)
    else
      @users = Kaminari.paginate_array(@users).page(params[:page]).per(25)
    end
  end

  def fetch_user
    @user = User.find(params[:user_id]).decorate
    respond_to { |format| format.js }
  end

  private

    def permitted_params
      params.permit(:state, :display_name, :city, :zip, :interest_types, :page).reject{|_, v| v.blank?}
    end
end

app/views/matchmakers/_links_in_popover.html.haml
- if user.user_status == 'enabled'
  =link_to 'View Profile', fetch_user_path(user_id: user.id), {"data-target" => "#profileModal", "data-toggle" => "modal", remote: true}
  %br
  - unless authenticated_user.display_name == user.display_name
    =link_to 'Send Message', new_conversation_path(recipient_id: user.id), target: '_blank'
    %br
    =link_to 'Add to Contacts', new_my_contact_path(contact_id: user.id), target: '_blank'

app/views/matchmakers/fetch_user.js.erb
$('#profile_partial').html("<%= j render(partial: 'profile/profile_modal', locals: { user: @user }) %>");
$('#profileModal').modal();
$('.matchmaker_popover').popover('hide');

app/views/matchmakers/index.html.haml
- page_title 'User Match'

%div#profile_partial
.container
  .row.pt-3.px-2.justify-content-center
    %h1.text-info User Match

  .row.pt-3
    .col
      %p.text-center.mb-2.p-2{style: "border: 1px solid black;"}
        %strong
          Search for Users in your area who have common interests, become acquainted, and plan activities together with this feature.

  .row.my-3
    .col
      = form_with url: [:matchmaker], method: :get, local: true do |f|
        .form-group.form-inline.justify-content-center#explore_communities_form
          %div.form-group.col-12.col-sm-12.col-md-2.col-lg-2
            = f.select(:state, US_STATES, {}, class: "form-control find_by_state", include_blank: 'State', style: "width: 100%;")
          %div.form-group.col-12.col-sm-12.col-md-4.col-lg-4
            = f.text_field :city, placeholder: 'City (note: case sensitive)', class: 'form-control find_by_city', style: "width: 100%;"
        %div.form-row
          %div.col-12
            .col-xs-3.col-md-3.col-sm-3.mx-auto
              = f.button "Search", class: "form-control btn btn-primary mb-3", style: 'border: 1px solid black;'
            %h3.notification-title.justify-content-center.mb-2
              %strong Participating Users
      %div.table-wrapper-2#events-feed{:style => "border-radius: 12px;"}
        %table.table.text-center
          %thead.mdb-color.lighten-4
            %tr
              %th
              %th Display Name
              %th
              %th City
              %th
              %th State
              %th
              %th Primary Interest
          %tbody
          - @users.each do |user|
            %tr
              %td
                %a{ class: 'matchmaker_popover c-pointer', tabindex: '0', role: 'button',
                    data: { toggle: 'popover', trigger: 'focus', content: "#{render 'links_in_popover',  user: user }" } }
                  - if user.avatar.attached?
                    = image_tag user.avatar, size: '50x50'
                  - else
                    = image_tag 'noavatar.png', size: '50x50'
              %td.font-weight-bold
                %a{ class: 'matchmaker_popover c-pointer', tabindex: '0', role: 'button',
                    data: { toggle: 'popover', trigger: 'focus', content: "#{render 'links_in_popover',  user: user }" } }
                  =user.display_name
              %td
              %td= user.city
              %td
              %td= user.state
              %td
              %td= user.interest_types
        %div.container.pagination.justify-content-center.pl-2
          %p= paginate @users unless @users.empty?
          - if @users.none?
            %p.text-muted.mb-3.text-center
              %em No search results.