config/routes.rb
Rails.application.routes.draw do
  root "public#index"

  get "cities/:state", to: "application#cities"

  # Public Pages
  get "about-us" => "public#about"
  get "careers" => "public#careers"
  get "join" => "public#join"
  get "service" => "public#service"
  get "service_highlights" => "public#service_highlights"
  get "service_screenshots" => "public#service_screenshots"
  get "participation" => "public#participation"
  get "affiliate_locator" => "public#affiliate_locator"
  get "affiliates" => "public#affiliates"
  get "member_locator" => "public#member_locator"
  get "members" => "public#members"
  get "pricing" => "public#pricing"
  get "news" => "public#news"
  get "affiliate_agreement" => "public#affiliate_agreement"
  get "saas_agreement" => "public#saas_agreement"
  get "terms" => "public#terms"
  get "privacy" => "public#privacy"
  get "faq" => "public#faq"

  # Create Member
  resources :members_registration, only: [:new, :create]

  # User Registration
  get "users_registration" => "users_registration#new"
  post "users_registration" => "users_registration#create"

  # Affiliate Registration
  get "affiliates_registration" => "affiliates_registration#new"
  post "affiliates_registration" => "affiliates_registration#create"

  #Stripe Webhooks
  mount StripeEvent::Engine, at: '/stripe_events'

  # Contact
  get "contact" => "contact#new"
  post "contact" => "contact#create"

  # Authentication vanity routes
  get "signin" => "sessions#new", as: "signin"
  delete "signout" => "sessions#destroy", as: "signout"

  # Authentication
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # My Profile
  get "my-profile" => "profile#edit", as: "profile"
  patch "profile" => "profile#update", as: "update_profile"
  get 'request_deactivation' => 'profile#new'
  post 'request_deactivation' => 'profile#create'

  # My Settings
  resource :my_settings, only: [:show, :update]

  # Matchmaker
  get 'matchmaker' => 'matchmakers#index'
  get 'fetch_user' => 'matchmakers#fetch_user'

  # Bulletin Board
  get 'bulletins' => 'bulletins#bulletins'

  # Verify ACH account
  resource :ach, controller: 'ach', only: [:edit, :update]

  # Communities
  resources :members, path: :communities, as: :community, controller: :communities do
    resources :events, only: [:index, :show] do
      post 'create_or_switch_rsvp', on: :member
    end
  end

  get 'explore_communities' => 'communities#explore_communities'
  get 'event_search' => 'communities#event_search'
  get 'leaderboard' => 'communities#leaderboard'
  get 'user_finder' => 'communities#user_finder'
  get 'event_suggestions' => 'communities#new'
  post 'event_suggestions' => 'communities#create'
  get 'announcement_suggestions' => 'communities#new_suggest'
  post 'announcement_suggestions' => 'communities#create_suggest'
  get 'challenge_new' => 'communities#challenge_new'
  get 'challenge_index' => 'communities#challenge_index'
  post 'challenge_new' => 'communities#challenge_create'
  get 'connection_index' => 'communities#connection_index'

  # Manage
  namespace :manage do
    get "member" => "member#edit", as: "edit_member"
    patch "member" => "member#update", as: "update_member"
    namespace :social_tracker do
      get "/:name/users" => "history#users", as: :users
      get "/:name/users/:id/history" => "history#user_history", as: :member_user
      get "/:name/users/:id/history/:id" => "history#show", as: :user_history
    end
    resources :events
    resources :announcements
    resources :challenges
    resources :connections
    resources :users do
      collection do
        get 'export_user_csv'
      end
    end
  end

  # Social Tracker
  namespace :social_tracker do
    get "log" => "events#new"
    post "log" => "events#create"
    get "history" => "events#index"
    get "history/:id" => "events#show"
  end

  # Social Fitness
  namespace :social_fitness do
    get "log" => "fitness#new"
    post "log" => "fitness#create"
    get "history" => "fitness#index"
    get "history/:id" => "fitness#show"
    get "plan" => "fitness#plan"
    get "console/fitness_plans/:id" => "fitness#plan_details", as: :plan_details
  end

  # Rewards
  get "rewards" => "rewards#index"

  # Dashboard
  get "home" => "home#index"

  # Console
  get "lookups" => 'console#lookups'
  get "console" => "console#index"
  namespace :console do
    root to: "console#index", as: "root"
    resources :affiliates do
      collection do
        get 'export_csv'
      end
    end
    resources :news
    resources :rewards
    resources :manage_bulletins
    resources :event_links
    resources :fitness_plans
    resources :notifications
    resources :members do
      collection do
        get 'export_global_user_csv'
        get 'export_user_csv'
        get 'export_member_csv'
      end
      resources :users
    end
    resources :users, path: :admins, as: :admins, controller: :admins
    namespace :social_tracker do
      get "members" => "history#members"
      get "members/:name/member_csv" => "history#member_csv", as: :member_csv
      get "members/:name/users" => "history#users", as: :member
      get "members/:name/users/:id/" => "history#user_history", as: :member_user
      get "members/:name/users/:user_id/history/:id" => "history#show", as: :member_user_social_event_log
      delete "members/:name/users/:user_id/history/:id" => "history#destroy", as: :delete_social_event_log
    end

    namespace :social_fitness do
      get "members" => "history#members"
      get "members/:name/member_csv" => "history#member_csv", as: :member_csv
      get "members/:name/users" => "history#users", as: :member
      get "members/:name/users/:id/" => "history#user_history", as: :member_user
      get "members/:name/users/:user_id/history/:id" => "history#show", as: :member_user_social_fitness_log
      delete "members/:name/users/:user_id/history/:id" => "history#destroy", as: :delete_social_fitness_log
    end
  end

  # Mailbox
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    post :mark_as_deleted, on: :collection
  end

  # Media Center
  get "media_center" => "media_center#index"

  # Help
  get "help" => "help#index"
  get 'service_support' => 'help#new'
  post 'service_support' => 'help#create'

  # My Bulletins
  resources :my_bulletins

  # Invite Guests
  get "invite_guests" => "invite_guests#new"
  post "invite_guests" => "invite_guests#create"

  # Invitation Reminder
  get "invitation_reminder" => "invitation_reminder#new"
  post "invitation_reminder" => "invitation_reminder#create"

  # Event Reminder
  get "event_reminder" => "event_reminder#new"
  post "event_reminder" => "event_reminder#create"

  # Share Link
  get "share_link" => "share_link#new"
  post "share_link" => "share_link#create"

  # Affiliates
  get "affiliates_search" => "affiliates#index"

  # Discounts
  get "discounts_finder" => "discounts_finder#index"

  # Event Links
  get "event_links" => "event_links#index"

  # Report Issues
  get "issues" => "issues#new"
  post "issues" => "issues#create"

  # My Achievements
  get "my_achievements" => "my_achievements#index"

  # My Events
  get "my_events" => "my_events#index"

  # Sitemap
  get "sitemap" => "sitemap#index"

  # My Contacts
  resources :my_contacts

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_authentication
  helper_method :sort_column, :sort_direction

  def index
    @notifications = Notification.order(created_at: :desc).page(params[:page]).per(10)
    @events = Event.joins(:rsvps).events_for_feed(authenticated_user.id).order("#{sort_column} #{sort_direction}").page(params[:event_page]).per(5)
    @social_event_Logs = SocialEventLog.where(user_id: authenticated_user.id)

    next_level = 10
    level = @social_event_Logs.size / next_level
    @level = level.floor
    @progress = (@social_event_Logs.size.modulo(next_level).round(2)) * next_level

  end

  private

  def sortable_columns
    %w[
      title start_at status
    ]
  end

  def sort_column
    logger.debug("SORT:::: #{params[:direction].inspect}")
    sortable_columns.include?(params[:column]) ? params[:column] : 'created_at'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    icon = sort_direction == 'asc' ? 'fas fa-arrow-up' : 'fas fa-arrow-down'
    icon = column == sort_column ? icon : ''
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/views/home/index.html.haml
- page_title 'Home'

.container
  .row.pt-3
    .col
      %h1.text-info.text-center Home

  .row.my-3
    .col
      %h3.notification-title.mb-2
        %strong Notifications
      #scroll-box.px-2{:style => "border-radius: 12px;"}
        - @notifications.each do |notification|
          .mb-3.text-center
            - if notification.special_notification==true
              %i.fas.fa-exclamation-triangle
            %h5= notification.title
            .notification-date= time_in_cdt(notification.updated_at, '%m/%d/%Y')
            .notification-text.text-left.pt-2.pb-2.border-top= simple_format(notification.body)
        %p= paginate @notifications
        - if @notifications.none?
          %p.mt-4.text-muted.text-center
            %em No notifications have been created.

    .col-12.pt-3
      %p.text-center
        =link_to 'Rewards Winners', rewards_path, class: 'btn btn-primary', style: 'border: 1px solid black'

  - if authenticated_user.hide_my_social_health==false
    .row.my-3
      .col
        %h3.notification-title.mb-2
          %strong My Social Health
        %div.table-wrapper-2.py-2#events-feed{:style => "border-radius: 12px;"}
          %h5.notification-title Social Health Level
          %span.social-health-experience-level.bg-primary.text-white{:style => "border-radius: 12px;"}
            = @level
          %h5.notification-title.mt-2 Social Health Level Progress
          %span.social-health-experience-experience
            %div.progress{ :style => "border: 1px solid black;" }
              %div.progress-bar{"aria-valuemax" => "100","aria-valuemin" => "0",
                                "aria-valuenow" => "#{@progress}", :role => "progressbar", :style => "width:#{@progress}%"}
                ="#{@progress}%"

      .col-12.pt-3
        %p.text-center
          =link_to 'Log Events', social_tracker_log_path, class: 'btn btn-primary', style: 'border: 1px solid black'

  - if authenticated_user.hide_my_social_events==false
    .row.my-3
      .col
        %h3.notification-title.mb-2
          %strong My Social Events
        %div.table-wrapper-2.table-hover#events-feed{:style => "border-radius: 12px;"}
          %table.table
            %thead.mdb-color.lighten-4.text-center
              %tr
                %th
                %th= sort_link 'title', 'Event Title'
                %th= sort_link 'start_at', 'Event Date/Time'
                %th RSVP
                %th
            %tbody
            - @events.each do |event|
              %tr.text-center.bg-white
                %td.c-pointer{:title => event.title}
                  - if event.logo.attached?
                    = link_to (image_tag event.logo, size: '50x50'), community_event_path(authenticated_user.member, event)
                  - else
                    = link_to (image_tag 'noimage.png', size: '50x50'), community_event_path(authenticated_user.member, event)
                %td.font-weight-bold.c-pointer{:title => event.title}= link_to "#{event.title}", community_event_path(authenticated_user.member, event)
                %td= short_date_time(event.start_at, event.time_zone)
                %td= home_events_status(event.status)
                %td.text-center
                  = link_to event_reminder_path(title: event.title, type: event.event_type, :location => event.location, :address => event.location_display, :start_at => (short_date_time(event.start_at, event.time_zone))), title: 'Event Reminder', class: 'btn btn-sm btn-outline-primary', style: 'border: 1px solid black' do
                    %i.fa.fa-bell
                    Event Reminder
              %tr.table-divider
          %p= paginate @events, param_name: :event_page
          - if @events.none?
            %div.text-muted.pb-3.text-center
              %em No RSVP'd events.

    .col-12.pb-3
      %p.text-center
        =link_to 'Event Search', event_search_path, class: 'btn btn-primary', style: 'border: 1px solid black'