config/routes.rb
Rails.application.routes.draw do
  root "public#index"

  get "cities/:state", to: "application#cities"

  # Public Pages
  get "about-us" => "public#about"
  get "careers" => "public#careers"
  get "join" => "public#join"
  get "service" => "public#service"
  get "service_highlights" => "public#service_highlights"
  get "service_screenshots" => "public#service_screenshots"
  get "participation" => "public#participation"
  get "affiliate_locator" => "public#affiliate_locator"
  get "affiliates" => "public#affiliates"
  get "member_locator" => "public#member_locator"
  get "members" => "public#members"
  get "pricing" => "public#pricing"
  get "news" => "public#news"
  get "affiliate_agreement" => "public#affiliate_agreement"
  get "saas_agreement" => "public#saas_agreement"
  get "terms" => "public#terms"
  get "privacy" => "public#privacy"
  get "faq" => "public#faq"

  # Create Member
  resources :members_registration, only: [:new, :create]

  # User Registration
  get "users_registration" => "users_registration#new"
  post "users_registration" => "users_registration#create"

  # Affiliate Registration
  get "affiliates_registration" => "affiliates_registration#new"
  post "affiliates_registration" => "affiliates_registration#create"

  #Stripe Webhooks
  mount StripeEvent::Engine, at: '/stripe_events'

  # Contact
  get "contact" => "contact#new"
  post "contact" => "contact#create"

  # Authentication vanity routes
  get "signin" => "sessions#new", as: "signin"
  delete "signout" => "sessions#destroy", as: "signout"

  # Authentication
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # My Profile
  get "my-profile" => "profile#edit", as: "profile"
  patch "profile" => "profile#update", as: "update_profile"
  get 'request_deactivation' => 'profile#new'
  post 'request_deactivation' => 'profile#create'

  # My Settings
  resource :my_settings, only: [:show, :update]

  # Matchmaker
  get 'matchmaker' => 'matchmakers#index'
  get 'fetch_user' => 'matchmakers#fetch_user'

  # Bulletin Board
  get 'bulletins' => 'bulletins#bulletins'

  # Verify ACH account
  resource :ach, controller: 'ach', only: [:edit, :update]

  # Communities
  resources :members, path: :communities, as: :community, controller: :communities do
    resources :events, only: [:index, :show] do
      post 'create_or_switch_rsvp', on: :member
    end
  end

  get 'explore_communities' => 'communities#explore_communities'
  get 'event_search' => 'communities#event_search'
  get 'leaderboard' => 'communities#leaderboard'
  get 'user_finder' => 'communities#user_finder'
  get 'event_suggestions' => 'communities#new'
  post 'event_suggestions' => 'communities#create'
  get 'announcement_suggestions' => 'communities#new_suggest'
  post 'announcement_suggestions' => 'communities#create_suggest'
  get 'challenge_new' => 'communities#challenge_new'
  get 'challenge_index' => 'communities#challenge_index'
  post 'challenge_new' => 'communities#challenge_create'
  get 'connection_index' => 'communities#connection_index'

  # Manage
  namespace :manage do
    get "member" => "member#edit", as: "edit_member"
    patch "member" => "member#update", as: "update_member"
    namespace :social_tracker do
      get "/:name/users" => "history#users", as: :users
      get "/:name/users/:id/history" => "history#user_history", as: :member_user
      get "/:name/users/:id/history/:id" => "history#show", as: :user_history
    end
    resources :events
    resources :announcements
    resources :challenges
    resources :connections
    resources :users do
      collection do
        get 'export_user_csv'
      end
    end
  end

  # Social Tracker
  namespace :social_tracker do
    get "log" => "events#new"
    post "log" => "events#create"
    get "history" => "events#index"
    get "history/:id" => "events#show"
  end

  # Social Fitness
  namespace :social_fitness do
    get "log" => "fitness#new"
    post "log" => "fitness#create"
    get "history" => "fitness#index"
    get "history/:id" => "fitness#show"
    get "plan" => "fitness#plan"
    get "console/fitness_plans/:id" => "fitness#plan_details", as: :plan_details
  end

  # Rewards
  get "rewards" => "rewards#index"

  # Dashboard
  get "home" => "home#index"

  # Console
  get "lookups" => 'console#lookups'
  get "console" => "console#index"
  namespace :console do
    root to: "console#index", as: "root"
    resources :affiliates do
      collection do
        get 'export_csv'
      end
    end
    resources :news
    resources :rewards
    resources :manage_bulletins
    resources :event_links
    resources :fitness_plans
    resources :notifications
    resources :members do
      collection do
        get 'export_global_user_csv'
        get 'export_user_csv'
        get 'export_member_csv'
      end
      resources :users
    end
    resources :users, path: :admins, as: :admins, controller: :admins
    namespace :social_tracker do
      get "members" => "history#members"
      get "members/:name/member_csv" => "history#member_csv", as: :member_csv
      get "members/:name/users" => "history#users", as: :member
      get "members/:name/users/:id/" => "history#user_history", as: :member_user
      get "members/:name/users/:user_id/history/:id" => "history#show", as: :member_user_social_event_log
      delete "members/:name/users/:user_id/history/:id" => "history#destroy", as: :delete_social_event_log
    end

    namespace :social_fitness do
      get "members" => "history#members"
      get "members/:name/member_csv" => "history#member_csv", as: :member_csv
      get "members/:name/users" => "history#users", as: :member
      get "members/:name/users/:id/" => "history#user_history", as: :member_user
      get "members/:name/users/:user_id/history/:id" => "history#show", as: :member_user_social_fitness_log
      delete "members/:name/users/:user_id/history/:id" => "history#destroy", as: :delete_social_fitness_log
    end
  end

  # Mailbox
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    post :mark_as_deleted, on: :collection
  end

  # Media Center
  get "media_center" => "media_center#index"

  # Help
  get "help" => "help#index"
  get 'service_support' => 'help#new'
  post 'service_support' => 'help#create'

  # My Bulletins
  resources :my_bulletins

  # Invite Guests
  get "invite_guests" => "invite_guests#new"
  post "invite_guests" => "invite_guests#create"

  # Invitation Reminder
  get "invitation_reminder" => "invitation_reminder#new"
  post "invitation_reminder" => "invitation_reminder#create"

  # Event Reminder
  get "event_reminder" => "event_reminder#new"
  post "event_reminder" => "event_reminder#create"

  # Share Link
  get "share_link" => "share_link#new"
  post "share_link" => "share_link#create"

  # Affiliates
  get "affiliates_search" => "affiliates#index"

  # Discounts
  get "discounts_finder" => "discounts_finder#index"

  # Event Links
  get "event_links" => "event_links#index"

  # Report Issues
  get "issues" => "issues#new"
  post "issues" => "issues#create"

  # My Achievements
  get "my_achievements" => "my_achievements#index"

  # My Events
  get "my_events" => "my_events#index"

  # Sitemap
  get "sitemap" => "sitemap#index"

  # My Contacts
  resources :my_contacts

end

app/controllers/console/admins_controller.rb
class Console::AdminsController < ConsoleController
  before_action :require_admin
  before_action :set_user_status, only: [:create, :update]
  helper_method :sort_column, :sort_direction

  def index
    @admins = User.where(admin: true)
    @admins = @admins.order("#{sort_column} #{sort_direction}").page(params[:page]).per(25)
  end

  def show
    @admin = User.find params[:id]
  end

  def new
    @admin = User.new
    @members = Member.order(:name)
  end

  def edit
    @admin = User.find params[:id]
    @members = Member.order(:name)
  end

  def create
    @admin = User.new(user_params)
    @admin.set_random_password

    if @admin.save
      redirect_to console_admin_url(@admin), success: 'The Admin was successfully created!'
    else
      @members = Member.order(:name)
      flash.now[:error] = 'Please correct the errors to continue.'
      render :new
    end
  end

  def update
    @admin = User.find params[:id]
    if @admin.update(user_params)
      redirect_to console_admin_url(@admin), success: 'The Admin was successfully updated!'
    else
      @members = Member.order(:name)
      flash.now[:error] = 'Please correct the errors to continue.'
      render :edit
    end
  end

  def destroy
    @admin = User.find params[:id]
    @admin.destroy
    redirect_to console_admins_url, success: 'The Admin was successfully deleted!'
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :display_name,
      :address,
      :city,
      :state,
      :zip,
      :phone,
      :gender,
      :ethnicity,
      :birthdate,
      :time_zone,
      :last_sign_in_at,
      :member_id,
      :user_status,
      :manager,
      :relationship_status,
      :education_level,
      :occupation,
      :languages,
      :hobbies,
      :pet_peeves,
      :user_status,
      :password,
      :password_confirmation,
      :interest_types,
      :group,
      :admin,
      :hide_info_on_user_finder,
      :hide_info_on_leaderboard,
      :hide_my_social_events,
      :hide_my_social_health
    )
  end

  def sortable_columns
    %w[
      name email display_name address city state zip phone gender interest_types
      ethnicity birthdate time_zone last_sign_in_at member_id user_status=1 manager
      admin
    ]
  end

  def sort_column
    logger.debug("SORT:::: #{params[:direction].inspect}")
    sortable_columns.include?(params[:column]) ? params[:column] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def set_user_status
    params[:user].merge!(user_status: params[:user][:user_status].to_i).permit!
  end

end

app/controllers/console/affiliates_controller.rb
class Console::AffiliatesController < ConsoleController
  before_action :require_admin
  helper_method :sort_column, :sort_direction
  
  def index
    @affiliates = Affiliate.order("#{sort_column} #{sort_direction}")
    @affiliates = FindUsersCommunities.new(@affiliates, show_init_scope: true).call(permitted_params)
    unless @affiliates.kind_of?(Array)
      @affiliates = @affiliates.page(params[:page]).per(25)
    else
      @affiliates = Kaminari.paginate_array(@affiliates).page(params[:page]).per(25)
    end
  end

  def show
    @affiliate = Affiliate.find params[:id]
  end

  def new
    @affiliate = Affiliate.new
  end

  def edit
    @affiliate = Affiliate.find params[:id]
  end

  def create
    @affiliate = Affiliate.new(affiliate_params)
    if @affiliate.save
      redirect_to console_affiliate_url(@affiliate), success: 'The Affiliate was successfully created!'
    else
      flash.now[:error] = 'Please correct the errors to continue.'
      render :new
    end
  end

  def update
    @affiliate = Affiliate.find params[:id]
    @affiliate.logo.attach(params[:affiliate][:logo]) if params[:affiliate][:logo]
    if @affiliate.update(affiliate_params)
      redirect_to console_affiliate_url(@affiliate.id), success: 'The Affiliate was successfully updated!'
    else
      @affiliate.logo.purge if @affiliate.errors.messages[:logo].present?
      flash.now[:error] = 'Please correct the errors to continue.'
      render :edit
    end
  end

  def destroy
    @affiliate = Affiliate.find params[:id]
    @affiliate.destroy
    redirect_to console_affiliates_url, success: 'The Affiliate was successfully deleted!'
  end

  def export_csv
    csv = helpers.csv_affiliate_list
    send_data csv, filename: "affiliates-#{Date.today}.csv"
  end

  private

  def permitted_params
    params.permit(:state).reject{|_, v| v.blank?}
  end

  def affiliate_params
    params.require(:affiliate).permit(
      :name,
      :address,
      :city,
      :state,
      :zip,
      :phone,
      :url,
      :hide_info_on_locator,
      :support_type,
      :contact_name,
      :contact_phone,
      :contact_phone_extension,
      :contact_email,
      :support_notes,
      :org_type,
      :date_added
    )
  end

  def sort_column
    logger.debug("SORT:::: #{params[:direction].inspect}")
    Affiliate::SORTABLE_COLUMNS.include?(params[:column]) ? params[:column] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

end

app/controllers/console/event_aggregators_controller.rb
class Console::EventAggregatorsController < ConsoleController
  helper_method :sort_column, :sort_direction
  before_action :find_resource, only: [:show, :edit, :update, :destroy]

  def index
    @resources = Resource.all.order("#{sort_column} #{sort_direction}")
    @resources = FindUsersCommunities.new(@resources, show_init_scope: true).call(permitted_params)
    unless @resources.kind_of?(Array)
      @resources = @resources.page(params[:page]).per(10)
    else
      @resources = Kaminari.paginate_array(@resources).page(params[:page]).per(10)
    end
  end

  def show
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(resource_params)
    if @resource.save
      redirect_to console_event_aggregators_path, success: 'The link was successfully created!'
    else
      flash.now[:error] = 'Please correct the errors to continue.'
      render :new
    end
  end

  def edit
  end

  def update
    if @resource.update(resource_params)
      redirect_to console_event_aggregator_path, success: 'The link was successfully updated!'
    else
      flash.now[:error] = 'Please correct the errors to continue.'
      render :edit
    end
  end

  def destroy
    @resource.destroy
    redirect_to console_event_aggregators_path, success: 'The link was successfully deleted!'
  end

  private

  def permitted_params
    params.permit(:city, :state).reject{|_, v| v.blank?}
  end

  def resource_params
    params.require(:resource).permit(:name, :event_type, :city, :state, :url)
  end

  def find_resource
    @resource = Resource.find(params[:id])
  end

  def sort_column
    %w[name event_type city state url].include?(params[:column])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

end

app/controllers/console/event_links_controller.rb
class Console::EventLinksController < ConsoleController
  helper_method :sort_column, :sort_direction
  before_action :find_resource, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  def index
    @resources = Resource.all.order("#{sort_column} #{sort_direction}")
    @resources = FindUsersCommunities.new(@resources, show_init_scope: true).call(permitted_params)
    unless @resources.kind_of?(Array)
      @resources = @resources.page(params[:page]).per(25)
    else
      @resources = Kaminari.paginate_array(@resources).page(params[:page]).per(25)
    end
  end

  def show
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(resource_params)
    if @resource.save
      redirect_to console_event_links_path, success: 'The link was successfully created!'
    else
      flash.now[:error] = 'Please correct the errors to continue.'
      render :new
    end
  end

  def edit
  end

  def update
    if @resource.update(resource_params)
      redirect_to console_event_link_path, success: 'The link was successfully updated!'
    else
      flash.now[:error] = 'Please correct the errors to continue.'
      render :edit
    end
  end

  def destroy
    @resource.destroy
    redirect_to console_event_links_path, success: 'The link was successfully deleted!'
  end

  private

  def permitted_params
    params.permit(:name, :city, :state).reject{|_, v| v.blank?}
  end

  def resource_params
    params.require(:resource).permit(:name, :event_type, :city, :state, :url, :notes, :member_id, :page)
  end

  def find_resource
    @resource = Resource.find(params[:id])
  end

  def sort_column
    %w[name event_type city state url].include?(params[:column]) ? params[:column] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

end

app/helpers/event_links_helper.rb
module EventLinksHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    icon = sort_direction == 'asc' ? 'fas fa-arrow-up' : 'fas fa-arrow-down'
    icon = column == sort_column ? icon : ''
    link_to "#{name} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/views/console/event_links/_form.html.haml
.row.justify-content-center.mb-3
  .col-md-8
    .card.card-box
      .card-body.justify-content-center.pt-0
      = form_with model: @resource, url: [:console_event_links], local: true do |f|
        .row.justify-content-center
          .col-lg-10
            * All fields are required
            .row.mt-2
            %h5 Event Link Information
            .form-group.mt-2
              %label(for="name") Event Site Name
              = f.text_field :name, autofocus: true, class: "form-control #{form_error_class(@resource, :name)}", required: true
              = model_error_display(@resource, :name)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="event_type") Event Type(s)
              = f.select :event_type, EVENT_TYPES, {}, { class: "#{form_error_class(@resource, :event_type)} form-control custom-select" }
              = model_error_display(@resource, :event_type)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="city") City
              = f.text_field :city, class: "form-control #{form_error_class(@resource, :city)}"
              = model_error_display(@resource, :city)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="state") State
              = f.select :state, US_STATES, { required: true }, { class: "#{form_error_class(@resource, :state)} form-control custom-select" }
              = model_error_display(@resource, :state)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="url") Website
              = f.text_field :url, class: "form-control #{form_error_class(@resource, :url)}", required: true
              = model_error_display(@resource, :url)

        .mb-3.text-center
          = f.submit 'Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }, style: 'border: 1px solid black;'
          = link_to 'Cancel', console_event_links_path, class: 'btn btn-outline-secondary', style: 'border: 1px solid black;'

app/views/console/event_links/edit.html.haml
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  %h1.h3.brand-primary Edit Link

.row.justify-content-center.mb-3
  .col-md-8
    .card.card-box
      .card-body.justify-content-center.pt-0
      = form_with model: @resource, url: [:console_event_link], local: true do |f|
        .row.justify-content-center
          .col-lg-10
            * All fields are required
            .row.mt-2
            %h5 Event Link Information
            .form-group.mt-2
              %label(for="name") Event Site Name
              = f.text_field :name, autofocus: true, class: "form-control #{form_error_class(@resource, :name)}", required: true
              = model_error_display(@resource, :name)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="event_type") Event Type(s)
              = f.select :event_type, EVENT_TYPES, {}, { class: "#{form_error_class(@resource, :event_type)} form-control custom-select" }
              = model_error_display(@resource, :event_type)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="city") City
              = f.text_field :city, class: "form-control #{form_error_class(@resource, :city)}"
              = model_error_display(@resource, :city)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="state") State
              = f.select :state, US_STATES, { required: true }, { class: "#{form_error_class(@resource, :state)} form-control custom-select" }
              = model_error_display(@resource, :state)

        .row.justify-content-center
          .col-lg-10
            .form-group
              %label(for="url") Website
              = f.text_field :url, class: "form-control #{form_error_class(@resource, :url)}", required: true
              = model_error_display(@resource, :url)

        .mb-3.text-center
          = f.submit 'Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' }, style: 'border: 1px solid black;'
          = link_to 'Cancel', console_event_link_path, class: 'btn btn-outline-secondary', style: 'border: 1px solid black;'

app/views/console/event_links/index.html.haml
- page_title 'Event Links'

%div#profile_partial
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-top.pb-3.border-bottom
  %h1.h3.brand-primary Event Links
  %div
    = link_to new_console_event_link_path, class: 'btn btn-primary', style: 'border: 1px solid black' do
      %i.fas.fa-plus-circle
      Add Link

.row.mt-2
  .col-12.col-md-4.col-lg-6
    %h5.pt-1.mb-0 Filter - By State
    .col-12.col.md-4.col-lg-6.justify-content-center
      = form_with url: [:console_event_links], method: :get, local: true do |f|
        .form-group.form-inline.justify-content-center#explore_communities_form
        = f.select(:state, US_STATES, {}, class: "form-control find_by_state", include_blank: 'State', style: "width: 100%;")
        %p
        = f.button "Filter", class: "form-control btn btn-primary mb-2", style: "border: 1px solid black"
        = link_to "Undo Filter", {:onclick => "history.go(0)" }, class: 'form-control btn btn-primary mb-3', style: 'border: 1px solid black'

- if @resources.any?
  .row.justify-content-center
    .table-responsive{ :style => 'border: 2px solid black; border-radius: 12px;' }
      %table.table.table-borderless.align-items-center.table-hover
        %thead
          %tr
            %th= sort_link 'title', 'Event Site Name'
            %th= sort_link 'event_type', 'Event Type(s)'
            %th= sort_link 'city', 'Event City'
            %th= sort_link 'state', 'Event State'
            %th= sort_link 'url', 'Website'
        %tbody
          - @resources.each.with_index(1) do |resource, i|
            %tr.bg-white
              %td= link_to truncate("#{i}. #{resource.name}"), console_event_link_path(resource)
              %td= resource.event_type
              %td= resource.city.presence || 'N/A'
              %td= resource.state
              %td= link_to "Visit Website", resource.url, target: :_blank
              %td.w-10.text-right
                .dropdown
                  = link_to '#', class: 'btn btn-sm btn-outline-primary dropdown-toggle dropdown-toggle-no-arrow', id: "dropdownMenuLink-#{resource.id}", data: { toggle: 'dropdown' }, 'aria-haspopup' => 'true', 'aria-expanded' => 'false' do
                    %i.fas.fa-ellipsis-h
                  .dropdown-menu.dropdown-menu-sm(aria-labelledby="dropdownMenuLink-#{resource.id}")
                    = link_to edit_console_event_link_path(resource), title: 'Edit', class: 'dropdown-item text-info' do
                      %i.far.fa-edit
                      Edit
                    = link_to console_event_link_path(resource), title: 'Delete', id: "delete_resource_#{resource.id}", class: 'dropdown-item text-danger', method: :delete, data: { confirm: 'Please confirm that you wish to delete this link. Press OK to continue.' } do
                      %i.far.fa-trash-alt
                      Delete
            %tr.table-divider
      %p= paginate @resources
- else
  %p.text-muted.text-center
    %em No links were found.

app/views/console/event_links/new.html.haml
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  %h1.h3.brand-primary Add Link

= render 'form'

app/views/console/event_links/show.html.haml
%nav(aria-label="breadcrumb")
  %ol.breadcrumb
    %li.breadcrumb-item= link_to 'Event Links', console_event_links_path

.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-top.mb-3.pb-3.border-bottom
  %h1.h3.brand-primary= @resource.name

.row.justify-content-center
  .col-9
    .settings-box.pt-0{:style => "border-radius: 12px;"}
      %p
      - if @resource.event_type.present?
        %strong Event Type(s):
        = @resource.event_type
      %p
      - if @resource.city.present?
        %strong  City:
        = @resource.city
      %p
      - if @resource.state.present?
        %strong  State:
        = @resource.state
      %p
      %p
        %strong  Website:
        = @resource.url

.container
  .col
    %div.form-row
      %div.float-left.py-3
        = link_to console_event_links_path, class: 'btn btn-outline-primary', style: 'border: 1px solid black;' do
          %i.fas.fa-arrow-left
          Back